### PR TITLE
Added proprt Sidebar, login and layout of home page

### PR DESCRIPTION
**Pull request by git-divyansh**
#5 Developed hompage sidebar

- Created an interactive sidebar with the following options: Home, My Polls, Create Poll, Search Polls, Profile. With responsive design, the sidebar should be collapsed into a hamburger menu icon on smaller screens. This makes the app more organized and accessible.

#7 Added the Login page

- Created basic layout for login page and validated email using regex. 
- Also created a baisc layout for the Home Page

### CODE REVIEW

**Comment by namansharma3007** [comment]
> #5 Developed hompage sidebar
> 
> * Created an interactive sidebar with the following options: Home, My Polls, Create Poll, Search Polls, Profile. With responsive design, the sidebar should be collapsed into a hamburger menu icon on smaller screens. This makes the app more organized and accessible.
> 
> #7 Added the Login page
> 
> * Created basic layout for login page and validated email using regex.
> * Also created a baisc layout for the Home Page

@git-divyansh Can you provide screen shot of your work.

**Comment by git-divyansh** [comment]
These are the screenshots for the changes made.

Screenshot (173)
Screenshot (171)
Screenshot (170)
Screenshot (169)

**Comment by namansharma3007** [comment]
Loved your work man
@git-divyansh 
I think you can also take on issue #14

**Comment by git-divyansh** [comment]
@namansharma3007  Sure!

**Pull request merged**
