### PR TITLE
Add Poll, Vote, Admin Model

### PR DESCRIPTION
**Pull request by skartik-sk**
Added Different Model for poll vote and Admin #11

### CODE REVIEW

**Comment by thefuadeniola** [comment]
@skartik-sk Nice models you've got there. For the vote model, it would be better if the type was a boolean and not a string. I assume you can only possibly upvote and downvote. This is also a quick commit you can make before your pr is merged!!

**Comment by skartik-sk** [comment]
Done Changes!
Is their anything else which is to be modified.

**Comment by thefuadeniola** [comment]
All good!

**Comment by namansharma3007** [comment]
@thefuadeniola Great Job

**Pull request merged**
